version: 0.0
os: linux
files:
  - source: ./cloudshape-1.0.0.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
